### PR TITLE
Remove svn dependency in default runs

### LINKED ISSUE #230: Remove dependency of checking out CABLE-AUX from SVN
Currently, a new user following the user guide in the [documentation](https://benchcab.readthedocs.io/en/stable/user_guide/) would need access to `cable` project group in NCI, irrespective of whether the `realisations` keyword has a svn repo. Since the CABLE project has been moved to Github, we want to remove the dependency of using SVN to checkout to `CABLE-AUX` branch by default.

**Reproducing the Bug**
1. Clone `CABLE-LSM/bench_example`
```sh
git clone git@github.com:CABLE-LSM/bench_example.git
```
2. Edit  `config.yml` to remove the svn realisation
```diff
-  - repo:
-      svn:
-        branch_path: trunk
```
3. Running `benchcab run` provides the following error:
```sh
[ag9761@gadi-login-02 bench_example]$ benchcab run
Creating src directory
Checking out repositories...
Successfully checked out main - commit 1c8a2cb763f0a797f78f23a3dd8296277f26bb86
Authentication realm: <https://trac.nci.org.au:443> NCI Projects
Password for 'ag9761': **********

Traceback (most recent call last):
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-23.10/bin/benchcab", line 10, in <module>
    sys.exit(main())
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-23.10/lib/python3.10/site-packages/benchcab/main.py", line 30, in main
    parse_and_dispatch(parser)
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-23.10/lib/python3.10/site-packages/benchcab/main.py", line 20, in parse_and_dispatch
    func(**args)
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-23.10/lib/python3.10/site-packages/benchcab/benchcab.py", line 317, in run
    self.fluxsite(config_path, no_submit, verbose, skip)
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-23.10/lib/python3.10/site-packages/benchcab/benchcab.py", line 302, in fluxsite
    self.checkout(config_path, verbose)
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-23.10/lib/python3.10/site-packages/benchcab/benchcab.py", line 201, in checkout
    cable_aux_repo.checkout(verbose=verbose)
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-23.10/lib/python3.10/site-packages/benchcab/utils/repo.py", line 186, in checkout
    self.subprocess_handler.run_cmd(cmd, verbose=verbose)
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-23.10/lib/python3.10/site-packages/benchcab/utils/subprocess.py", line 62, in run_cmd
    proc = subprocess.run(cmd, shell=True, check=True, **kwargs)
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-23.10/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'svn checkout https://trac.nci.org.au/svn/cable/branches/Share/CABLE-AUX src/CABLE-AUX' returned non-zero exit status 1.
```

**Further Steps**
The behaviour may have to do something with checking out the svn branch stored in `cable_aux_repo`:
https://github.com/CABLE-LSM/benchcab/blob/af43dad820811bc0b5e56161957ca374aeeb704e/benchcab/benchcab.py#L197

### PR DESCRIPTION
**Pull request by abhaasgoyal**
Fixes #230 

**Merge Message**
When running benchcab, it checks out on svn branch, potentially for data files like `GRID_DATA`. This commit:
- Removes the dependency to check out in svn branch
- Cleans up internal variables for unused files
- Uses alternative sources for existing data files in svn - testing was done via bitwise comparison generated by `main` vs `230-remove-svn-dependency` branch during integration tests

### CODE REVIEW

**Comment by abhaasgoyal** [comment]
@ccarouge can you run benchcap for comparison on CABLE_AUX?

**Comment by ccarouge** [comment]
Comparison of benchcab with the gridinfo file from CABLE-AUX branch or from rp23 has been done. It has shown differences in the results. This is surprising and might require further investigation on CABLE-side later on.
To move on here, we will look at adding the CABLE-AUX data under /g/data/wd9 for the moment. This will change once we have a well-documented gridinfo file we can use instead.

File: benchcab/data/test/integration.sh [hunk 1]
```diff
@@ -39,6 +32,7 @@ fluxsite:
   experiment: AU-Tum
   pbs:
     storage:
+      - gdata/wd9
```
Comment (ccarouge) [inline benchcab/data/test/integration.sh:35]: This needs to be added to `render_job_script()` in `pbs.py` with the other storage flags. It isn't a user entry because benchcab would fail if it is missing. 

We need to change all these hard-coded data to be handled differently, but that's another issue.

**Review by ccarouge — APPROVED** [review]
There is one small change to make before merging. I'm approving because I don't think I need to review again after that change but feel free to ask anyway if you want to.

Once the change is done, you are free to merge (not squash or rebase please).

File: benchcab/data/test/integration.sh (hunk 1 above)
Comment (ccarouge) [reply benchcab/data/test/integration.sh:35]: And it should be removed from `integration.sh`

Comment (abhaasgoyal) [reply benchcab/data/test/integration.sh:35]: Do we assume access to `ks32` for `wd9` (can write it off as a comment)
